# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: build
  jobs:
  - job: job1
    steps:
    - bash: echo build first job
    - bash: ls -R $
    - bash: java -version
    - bash: node --version
    - bash: mvn -version
    - bash: python --version
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
    - bash: ls -R $(Build.ArtifactStagingDirectory)
