# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: build
  jobs:
  - job: job1
    steps:
    - bash: echo build first job
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.Repository.Name)
    - bash: echo $(Build.SourcesDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
    