# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: build
  jobs:
  - job: job1
    steps:
    - bash: echo build job1
  - job: job2
    steps:
    - bash: echo build job2
- stage: DevDeploy
  dependsOn: build
  jobs:
  - job: job1
    steps:
    - bash: echo DevDeploy job1
  - job: job2
    steps:
    - bash: echo DevDeploy job2
- stage: QADeploy
  dependsOn: build
  jobs:
  - job: job1
    steps:
    - bash: echo QADeploy job1
  - job: job2
    steps:
    - bash: echo QADeploy job2
- stage: prodDeploy
  dependsOn:
  - build
  - QADeploy
  - DevDeploy
  jobs:
  - job: job1
    steps:
    - bash: echo ProdDeploy job1
  - job: job2
    steps:
    - bash: echo ProdDeploy job2
